services:
  nginx-rtmp:
    build: .
    ports:
      - "1935:1935"  # Puerto RTMP
      - "80:80"     # Puerto HTTP para DASH/HLS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
      - ./dash:/tmp/dash
      - ./hls:/tmp/hls
    restart: unless-stopped
